"""
engine.py
Updated LangGraph logic for ClientScout.
Uses the current 2026 'prompt' standard for create_react_agent.
"""

import os
from dotenv import load_dotenv
from langchain_groq import ChatGroq
from langchain_community.utilities import DuckDuckGoSearchAPIWrapper
from langchain_core.tools import tool
from langgraph.prebuilt import create_react_agent
from langchain_core.messages import HumanMessage, SystemMessage

# Load environment variables
load_dotenv()

@tool
def search_internet(query: str) -> str:
    """Searches the live internet."""
    print(f"DEBUG: Searching for -> {query}") # Add this line
    try:
        # Lower the max_results to 3 to speed it up for the demo
        wrapper = DuckDuckGoSearchAPIWrapper(max_results=3) 
        return wrapper.run(query)
    except Exception as e:
        return f"SEARCH FAILURE: {str(e)}"

def invoke_agent(company_name: str) -> str:
    """
    Initializes the LangGraph agent using the modern 'prompt' parameter.
    """
    # 1. Initialize LLM
    llm = ChatGroq(
        model="llama-3.3-70b-versatile",
        temperature=0.2,
        max_tokens=1024
    )

    # 2. Define the rulebook as a SystemMessage
    # This is the most reliable way to enforce behavior in LangGraph 2026
    instructions = SystemMessage(content="""You are ClientScout, an elite B2B Intelligence Agent.
    Use the search_internet tool to research the requested company.
    
    CRITICAL: You must use the provided tools to get information. Do not explain your reasoning in XML. Use the standard tool-calling schema. If you fail to call a tool, the mission fails.

    If your first search for '[Company Name]' yields no specific results, immediately perform a second search for '[Company Name] official website' or '[Company Name] LinkedIn' to extract data. NEVER say you can't find info. If you find nothing, infer their business based on their name or sector-wide trends.
                                                              
    STRICT OUTPUT FORMAT (Markdown):
    ### [Company Name] | Corporate Intelligence Report
    ---
    #### 🎯 1. Core Business & Value Proposition
    * [Bullet points explaining what they do and who they serve]
    
    #### 📰 2. Recent Strategic Developments
    * [List major news, funding, or leadership changes from the last 12 months]
    
    #### 🛠️ 3. Probable IT & Operational Challenges
    * [Analyze their tech stack/industry to infer challenges like Scalability, Legacy System Migration, or Cybersecurity]
    
    ---
    *Confidential Analysis for Lead Architect*
    
    INSTRUCTION: Do not return paragraphs. Use bold headers and bullet points. If you cannot find live news, provide an 'Industry Standard Analysis' for their specific sector.*""")

    # 3. Assemble the Agent
    # We use 'prompt' here as 'state_modifier' is now deprecated/removed
    agent = create_react_agent(
        model=llm, 
        tools=[search_internet], 
        prompt=instructions
    )

# 4. Execute the Graph
    try:
        # We convert the generator to a list and take the last event
        # This works whether you're using a basic agent or a stateful one
        events = list(agent.stream(
            {"messages": [HumanMessage(content=f"Research this company: {company_name}")]},
            stream_mode="values"
        ))
        
        if events:
            # The last event in 'values' mode is the full final state
            final_state = events[-1]
            return final_state["messages"][-1].content
        else:
            return "ERROR: No response generated by the agent."
            
    except Exception as e:
        return f"CRITICAL SYSTEM FAILURE: {str(e)}"